name = "rocket-science"
version = "1.0.0"
license = "BSD"
author = ["Damian Rouson", "Brad Richardson", "Brian Laubacher"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2020-2021 Sourcery Institute"

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.2.1"}
